Repository DKT-Kwanza/dmarket-front, pull requests merged in 2024-02, with the labels that each got.

#208 [feat] cypress 전체 테스트
  cypress/e2e/DetailPage.cy.js
  cypress/e2e/all.cy.js
  src/App.js
  src/components/user/Common/Button/ScrollToTopBtn.css
Labels: 🎀marie🎀, feat ✨

#209 [mod] nginx 파일 수정 및 추천 상품 안보이는 오류 수정
  Dockerfile
  nginx.conf
  src/components/user/Item/DetailQnaListItem.jsx
  src/components/user/Item/QnaItem.jsx
  src/components/user/List/DetailQnaList.jsx
  src/components/user/List/RecommendProductList.jsx
  src/pages/admin/Member/UserPage.jsx
  src/pages/user/Product/DetailPage.jsx
Labels: 🎀marie🎀, mod 〰️

#211 [mod] nginx.conf 주석 변경
  nginx.conf
Labels: jupiter, merge 🔀, mod 〰️

#214 [fix] 오류 수정
  src/components/user/Common/Modal/NotificationModal.jsx
  src/components/user/List/RecommendProductList.jsx
Labels: 🎀marie🎀, fix 💥

#216 [fix] 검색 리스트 수정
  src/pages/user/Product/SearchPage.jsx
Labels: 🎀marie🎀, fix 💥

#218 [docs] #217 README.md 파일 수정
  README.md
Labels: kai🐣, docs 📄

#219 [docs] #217 README.md 파일 수정
  README.md
Labels: kai🐣, docs 📄
